/* Generated by Nim Compiler v1.6.6 */
/* Compiled for: Android, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3   -I/data/data/com.termux/files/usr/lib/nim/lib -I/data/data/com.termux/files/home/ngfx/generator -o /data/data/com.termux/files/home/ngfx/generator/cache/stdlib_os.nim.c.o /data/data/com.termux/files/home/ngfx/generator/cache/stdlib_os.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
extern NCSTRING* environ;
extern int cmdCount;
extern NCSTRING* cmdLine;
